### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by trungtle** [WebGLSamples/WebGL2Samples#1]
# OpenGL ES 3 Feature Lists
### Texturing
- [x] sRGB textures and framebuffers: gamma-correction
- [x] 2D texture arrays: texture animation
- [x] 3D textures: 3D voxel data, medical imaging
- [x] Depth textures and shadow comparison: Shrek :x: supported in webgl1
- [x] Seamless cubemaps: :x: no need for a sample
- [x] Floating-point textures
- [x] ETC2/EAC texture compression : Shrek
- [x] Integer textures
- [x] Additional texture formats
- [x] Non-power-of-2 textures: :x: no need for a sample, texture-2d-array is already using non-power of two texture
- [x] Texture level of detail (LOD) features
- [x] Texture swizzles: independent control of each RGBA channel: :x: Not supported
- [x] Immutable textures: Trung
- Increased minimum sizes : :x: no need for a sample
### Shaders
- [x] Program binaries: Trung :x: Skipping this (http://blog.tojicode.com/2013/09/whats-coming-in-webgl-20.html)
- Mandatory online compiler : Shrek :grey_question: no need for a sample?
- [x] Non-sqaure matrices: Trung :grey_question: no need for a sample? matCxR simply just use it in the shader?
- [x] Full integer support : Shrek : already has a texture_integer
- [x] Centroid sampling: Shrek
- [x] Flat/smooth interpolators: Shrek
- [ ] Uniform blocks: Shrek : :zzz: Pending Having trouble doing this one, also this fails the conformance test
- [x] Layout qualifers: :x: no need for a sample: Trung
- [x] Instance and vertexID
- Fragment depth: Trung : :x: webgl 1 supported
- [x]  New built-in functions : Shrek
-  Relaxed limitations: :x: no need for a sample: Trung
### Geometry
- [x] Transform feedback
- [x] Boolean occlusion queries : Shrek
- [x] Instanced rendering: Trung
- [ ] Primitive restart : Shrek  :zzz:Pending, the conformance test fail on this
- [x] New vertex formats: Trung
### Buffer Objects
- Uniform buffer objects : Shrek The same as Uniform blocks
- [x] Vertex array objects: Trung
- [x] Sampler objects : Shrek
- [x] Sync objects: Trung
- [ ] Pixel buffer objects: asynchronous transfer of data : Shrek :zzz:Pending, the conformance test fail on this
- Buffer subrange mapping: Not available on WebGL 2. Replaced by getBufferSubData. Trung
- [x] Buffer object to buffer object copies : Shrek
### Framebuffer
- [x] Multiple render targets (MRTs)
- [x] Multisample renderbuffer : Shrek
- [ ] Framebuffer invalidation hints : Trung
- [x] New blend equations  : Shrek
# Background

[WebGL 2.0 Spec](https://www.khronos.org/registry/webgl/specs/latest/2.0/)
[SIGGRAPH Asia 2015](https://docs.google.com/presentation/d/1Orx0GB0cQcYhHkYsaEcoo5js3c5-pv7ahPniIRIzzfg/edit?usp=sharing)
### Feature set new in OpenGL ES 3.0:
- Many sized texture formats (including integer and float textures), 3D textures, 2D texture arrays, immutable textures, more compressed texture formats
  - Full non-power-of-two texture support
- Instanced drawing*
- Multiple render targets*
- Transform feedback
- True integer vertex attributes
- Multisampled renderbuffers
- Shading language upgrades
  - texture level-of-detail sampling control (important for physically based rendering pipelines)
  - uniform blocks
  - in/out variables instead of “attribute”, etc.
  - control over layout in the shader
- Seamless cubemaps
  - Important for physically based rendering pipelines; can finally use mipmap generation effectively
- More GPU to GPU paths
  - Upload textures from pixel unpack buffers, read pixels into pixel pack buffers, copying between buffers
  - Transform feedback
  - When used in conjunction with 3D textures and 2D texture arrays, have much more computation ability than WebGL 1.0
- Features for performance optimization:
  - Uniform buffers
  - Vertex array objects*
- Convenience features:
  - Sampler objects
- Query objects
- Sync objects
# Samples

Our current plan is to base of a subset of Christophe's [OpenGL Samples Pack](https://github.com/g-truc/ogl-samples)

Current planning [google sheet](https://docs.google.com/spreadsheets/d/1NCW74tODvWpZ1NQoVIgZF1QFVCYo1XaQls-MrRYa8C0/edit?usp=sharing) in details. If you have comments and inputs, please add to this doc. Lots more to come!
# Schedule and Task
- **Dec 14** Set up the framework for the samples
- **Dec 22** Test with first sample, figure out what ten samples to implement
- **Dec 31** Implement the first 10 samples
- **Jan 7** Implement samples labeled WIP in [google sheet](https://docs.google.com/spreadsheets/d/1NCW74tODvWpZ1NQoVIgZF1QFVCYo1XaQls-MrRYa8C0/edit?usp=sharing) (8 in total)
- **Jan 12** Implement samples labeled WIP in [google sheet](https://docs.google.com/spreadsheets/d/1NCW74tODvWpZ1NQoVIgZF1QFVCYo1XaQls-MrRYa8C0/edit?usp=sharing)  (6 in total)
- **Jan 20** Implement samples according to OpenGL ES 3 feature list (4 in total), clean issues. 
- **Jan 27** Implement samples according to OpenGL ES 3 feature list (4 in total), clean issues
- **Jan 31** code sprint, Implement samples according to OpenGL ES 3 feature list (4 in total)， clean issues
- **Feb 7** Implement samples according to OpenGL ES 3 feature list (4 in total), clean issues
- **Feb 15**  glsl-New built-in functions, New vertex formats, Finish WebGL 2 Sample Pack, start glTF work.

**Comment by pjcozzi** [comment]
Great job with this and the spreadsheet!

Make sure to check Section 5 (Differences Between WebGL and OpenGL ES 3.0) of the WebGL 2 spec to help understand what OpenGL samples will require more work to port (or should not be ported).

Keep, the framework as simple and lightweight as possible.  Helper functions for compiling/linking shaders, for example, are great, but do not abstract WebGL much since your target audience is mostly WebGL engine developers who will want to see the raw WebGL functions in a simple and easy-to-follow manner.

For vertex and matrix types, I recommend http://glmatrix.net/

Make the README.md concise and direct.  Include all the instructions necessary for developers to get started with the samples and contribute to them.  Also host them with [GitHub pages](https://pages.github.com/) so most users can simply "view source" or step through the examples in the debugger without downloading a zip or cloning a repo.

Please prominently credit Christophe and the OpenGL Samples Pack.

Questions:
- What are the first 10 samples you plan to write?  Think about which will be easy for you to get started with, are already implemented in the browsers, and will be useful to the WebGL community.
- Of these examples, which will be first?
- When do you plan to finish them?

Once you finish the first 10, we will create a schedule for the rest.

**Comment by pjcozzi** [comment]
If you need a simple UI for any demos, see https://code.google.com/p/dat-gui/

**Comment by pjcozzi** [comment]
Also, this is a great reference on OpenGL ES 3: https://www.khronos.org/opengles/sdk/docs/man3/

**Comment by pjcozzi** [comment]
@shrekshao @trungtle let me know when this is updated with the schedule leading up to GDC as we discussed offline.

**Comment by shrekshao** [comment]
plan is updated

**Comment by pjcozzi** [comment]
Looks good, thanks!

**Comment by pjcozzi** [comment]
For glTF support before GDC:
- Reading and Tools
  - To test a glTF model, drag and drop it [here](http://cesiumjs.org/convertmodel.html)
  - For an overview of glTF, see [here](https://www.khronos.org/assets/uploads/developers/library/overview/glTF-1.0-Introduction-Oct15.pdf)
  - For the full details, the [spec](https://github.com/KhronosGroup/glTF/blob/master/specification/README.md) is a short read (ignoring the properties reference)
  - There are several JavaScript glTF, review the [Cesium loader or others](https://github.com/KhronosGroup/glTF#loaders-and-viewers).  **Recall that the goal of our loader is to be as simple as possible and fully spec compliant so it can serve as a reference loader for everyone.** 
- Implementation
  - Convert OBJs in this repo to glTF using [OBJ2GLTF](https://github.com/AnalyticalGraphicsInc/OBJ2GLTF)
  - Remove the third-party WebGL loader (remove the file and reference in the LICENSE.md)
  - Create a geometry-only glTF loader as a single.js file in the `samples/third-party` directory for now (we'll give it its own repo after GDC)
  - Do not worry about loading shaders/texture/techniques/materials, animations/skins, cameras, etc.  Instead, focus on walking the node hierarchy and loading the geometry.
  - Research how well modern web browsers support data URIs.  If support is still poor, use https://github.com/AnalyticalGraphicsInc/gltf-utilities

**Comment by pjcozzi** [comment]
OK to close this?

**Comment by shrekshao** [comment]
Fine for me

**Comment by trungtle** [comment]
Yes
